# Generated by Django 5.0 on 2023-12-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
